config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home' #(creates root_path)
  get '/help', to: 'static_pages#help' #(help_path)
  get '/about', to: 'static_pages#about' #(about_path)
  get '/contact', to: 'static_pages#contact' #(contact_path)
  get '/signup', to: 'users#new'  #a signup is really creating a user object
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new' #sessions controller handles logging
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users #maybe clean up new and create routes
  resources :barks, only: [:index, :create, :edit, :update, :destroy]
  resources :likes, only: [:create, :destroy]
  post "/likes/:id", to: 'likes#destroy'
  resources :parks
  resources :reviews, only: [:create, :edit, :destroy, :update]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/park.rb
class Park < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :address, presence: true, uniqueness: true
  validates :description, presence: true, length: { maximum: 255 }

  has_many :reviews
  has_many :users, through: :reviews

  def self.all_with_reviews
    self.all.select do |p|
      if p.reviews.size > 0
        p
      end
    end
  end

  def self.sorted_by_overall_average
    self.all_with_reviews.sort {|a, b| b.overall_average <=> a.overall_average}
  end

  def self.sorted_by_energy_level_average
    self.all_with_reviews.sort {|a, b| b.energy_level_average <=> a.energy_level_average}
  end

  def self.sorted_by_facilities_average
    self.all_with_reviews.sort {|a, b| b.facilities_average <=> a.facilities_average}
  end

  def self.sorted_by_scene_average
    self.all_with_reviews.sort {|a, b| b.scene_average <=> a.scene_average}
  end

  def overall_average
    self.reviews.average(:overall)
  end

  def energy_level_average
    self.reviews.average(:energy_level)
  end

  def facilities_average
    self.reviews.average(:facilities)
  end

  def scene_average
    self.reviews.average(:scene)
  end

  def most_freq_overall_rating
    arr = self.reviews.map do |r|
      r.overall
    end
    freq = arr.inject(Hash.new(0)) { |h,v| h[v] += 1; h }
    arr.max_by { |v| freq[v] }
  end

  def most_freq_energy_level_rating
    arr = self.reviews.map do |r|
      r.energy_level
    end
    freq = arr.inject(Hash.new(0)) { |h,v| h[v] += 1; h }
    arr.max_by { |v| freq[v] }
  end

  def most_freq_facilities_rating
    arr = self.reviews.map do |r|
      r.facilities
    end
    freq = arr.inject(Hash.new(0)) { |h,v| h[v] += 1; h }
    arr.max_by { |v| freq[v] }
  end

  def most_freq_scene_rating
    arr = self.reviews.map do |r|
      r.scene
    end
    freq = arr.inject(Hash.new(0)) { |h,v| h[v] += 1; h }
    arr.max_by { |v| freq[v] }
  end

end

app/controllers/parks_controller.rb
class ParksController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]

  def index
    @parks = Park.all
    @overall_parks = Park.sorted_by_overall_average[0..2]
    @energy_parks = Park.sorted_by_energy_level_average[0..2]
    @facilities_parks = Park.sorted_by_facilities_average[0..2]
    @scene_parks = Park.sorted_by_scene_average[0..2]
  end

   def new
     @park = Park.new
   end

  def create
    @park = Park.new(park_params)
    if @park.save
      flash[:success] = "Ruff!"
      redirect_to parks_path
    else
      redirect_to request.referrer
    end
  end

  def edit
    @park = Park.find(params[:id])
  end

  def update
    @park = Park.find(params[:id])
    if @park.update_attributes(park_params)
      flash[:success] = "Ruff"
      redirect_to @park
    else
      render 'edit'
    end
  end

  def show
    @park = Park.find(params[:id])
    @review = @park.reviews.build if logged_in?
    @reviews = @park.reviews.limit(5)
  end

  def destroy
    @park = Park.find(params[:id])
    @park.destroy
    flash[:success] = "Ruff"
    redirect_to request.referrer
  end

  private

  def park_params
    params.require(:park).permit(:name, :address, :description, :latitude, :longitude)
  end


end

app/views/parks/_form.html.erb
<%= form_for(@park) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :address %>
  <%= f.text_field :address, class: 'form-control' %>

  <%= f.label :description %>
  <%= f.text_area :description, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/parks/_park.html.erb
<li>
  <%= link_to park.name, park %>
  <br>
  <% if park.reviews.any? %>
  Overall Rating: <%= number_with_precision(park.overall_average, precision: 1) %> | <%=park.reviews.count%> reviews
  <% end %>
  <% if current_user.admin?%>
    | <%= link_to "delete", park, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/parks/edit.html.erb
<% provide(:title, 'Edit park') %>
<% provide(:button_text, 'Save changes') %>
<h1>Update your profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/parks/index.html.erb
<% provide(:title, 'All Parks') %>
<%=link_to "Add New Park", new_park_path %>

<h1>Highest Overall Rating</h1>
<ul class="barks">
  <% @overall_parks.each do |park| %>
    <li><%= link_to park.name, park %><br>
    Overall Rating: <%= number_with_precision(park.overall_average, precision: 1) %> | <%=park.reviews.count%> reviews </li>
  <% end %>
</ul>

<h1>Parks with Highest Energy Level</h1>
<ul class="barks">
  <% @energy_parks.each do |park| %>
    <li><%= link_to park.name, park %><br>
    Energy Level Rating: <%= number_with_precision(park.energy_level_average, precision: 1) %> | <%=park.reviews.count%> reviews </li>
  <% end %>
</ul>

<h1>Best Parks to Take a Doopsa</h1>
<ul class="barks">
  <% @facilities_parks.each do |park| %>
    <li><%= link_to park.name, park %><br>
    Facilities Rating: <%= number_with_precision(park.facilities_average, precision: 1) %> | <%=park.reviews.count%> reviews </li>
  <% end %>
</ul>

<h1>Best Parks for Meeting Other Dogs</h1>
<ul class="barks">
  <% @scene_parks.each do |park| %>
    <li><%= link_to park.name, park %><br>
    Scene Rating: <%= number_with_precision(park.scene_average, precision: 1) %> | <%=park.reviews.count%> reviews </li>
  <% end %>
</ul>

<h1>All Parks</h1>
<ul class="barks">
  <%= render @parks %>
</ul>

app/views/parks/new.html.erb
<% provide(:title, 'Add Park') %>
<% provide(:button_text, 'Add Park') %>
<h1>Create a Dog Park</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/parks/show.html.erb
<% provide(:title, @park.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= render 'shared/park_info' %>
    </section>
    <h4>Create a Review</h4>
    <section class="review_form">
      <% provide(:button_text, 'Add Review!') %>
      <%= render 'shared/review_form' %>
    </section>
  </aside>
  <div class="col-md-8">
      <h3>Description</h3>
      <span class="description"><%= @park.description%></span>
      <% if @park.reviews.count > 0 %>
        <div class="rating">
          <br>
          <span>Overall Rating: <%= number_with_precision(@park.overall_average, precision: 1)%> <% if current_user.admin? %> | Most Common: <%= @park.most_freq_overall_rating %> <% end %></span><br>
          <span>Energy Level: <%= number_with_precision(@park.energy_level_average, precision: 1)%> <% if current_user.admin? %> | Most Common: <%= @park.most_freq_energy_level_rating %> <% end %></span><br>
          <span>Facilities: <%= number_with_precision(@park.facilities_average, precision: 1)%> <% if current_user.admin? %> | Most Common: <%= @park.most_freq_facilities_rating %> <% end %></span><br>
          <span>Scene: <%= number_with_precision(@park.scene_average, precision: 1)%> <% if current_user.admin? %> | Most Common: <%= @park.most_freq_scene_rating %> <% end %></span><br>
        </div>
        <% else %>
      <% end %>
      <h3>Reviews (<%= @park.reviews.count %>)</h3>
      <% if @park.reviews.count > 0 %>
        <ol class="barks">
          <%= render @reviews %>
        </ol>
      <% end %>
  </div>
</div>