config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home' #(creates root_path)
  get '/help', to: 'static_pages#help' #(help_path)
  get '/about', to: 'static_pages#about' #(about_path)
  get '/contact', to: 'static_pages#contact' #(contact_path)
  get '/signup', to: 'users#new'  #a signup is really creating a user object
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new' #sessions controller handles logging
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users #maybe clean up new and create routes
  resources :barks, only: [:index, :create, :edit, :update, :destroy]
  resources :likes, only: [:create, :destroy]
  post "/likes/:id", to: 'likes#destroy'
  resources :parks
  resources :reviews, only: [:create, :edit, :destroy, :update]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_bark_form.html.erb
<%= form_for(@bark) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Woof..." %>
  </div>
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_park_info.html.erb
<h1><%= @park.name %></h1>
<p class="address"><%= @park.address%><br>
<%=link_to "edit", edit_park_path(@park) %>
</p>

app/views/shared/_review_form.html.erb
<%= form_for(@review) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.hidden_field :park_id, value: @park.id %>

  <%= f.label :overall %>
  <%= f.select :overall, options_for_select([["Select One", ""], ['1', 1], ['2', 2], ['3', 3], ['4', 4], ['5', 5]]), class: 'form-control' %>

  <%= f.label :energy_level %>
  <%= f.select :energy_level, options_for_select([["Select One", ""], ['1', 1], ['2', 2], ['3', 3], ['4', 4], ['5', 5]]), class: 'form-control' %>

  <%= f.label :facilities %>
  <%= f.select :facilities, options_for_select([["Select One", ""], ['1', 1], ['2', 2], ['3', 3], ['4', 4], ['5', 5]]), class: 'form-control' %>

  <%= f.label :scene %>
  <%= f.select :scene, options_for_select([["Select One", ""], ['1', 1], ['2', 2], ['3', 3], ['4', 4], ['5', 5]]), class: 'form-control' %>

  <%= f.label :content %>
  <%= f.text_area :content, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<% if @user.image.profile.url != nil %>
  <%= image_tag @user.image.profile.url %>
<% end %>
<h1><%= @user.name %></h1>
<span><%= link_to "view my profile", @user %></span>
<span><%= pluralize(@user.barks.count, "bark") %></span>